# Generated by Django 3.1.4 on 2024-05-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_offers_button_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='message',
            name='wp',
        ),
    ]
